// <auto-generated />
using System;
using MajorProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MajorProject.Migrations
{
    [DbContext(typeof(MajorProjectDbContext))]
    [Migration("20220819114232_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MajorProject.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarMID")
                        .HasColumnType("int");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("CarMID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("MajorProject.Models.CarCompany", b =>
                {
                    b.Property<int>("CarCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarCompanies")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(15);

                    b.HasKey("CarCompanyId");

                    b.ToTable("CarCompanies");
                });

            modelBuilder.Entity("MajorProject.Models.CarModel", b =>
                {
                    b.Property<int>("CarCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarCID")
                        .HasColumnType("int");

                    b.Property<string>("CarModels")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(15);

                    b.HasKey("CarCompanyId");

                    b.HasIndex("CarCID");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("MajorProject.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MajorProject.Models.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Car")
                        .HasColumnType("int");

                    b.Property<int>("IssueCategory")
                        .HasColumnType("int");

                    b.Property<string>("Services")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.HasIndex("Car");

                    b.HasIndex("IssueCategory");

                    b.HasIndex("Urgency");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("MajorProject.Models.IssueCategory", b =>
                {
                    b.Property<int>("IssueCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IssueCategoryId");

                    b.ToTable("IssueCategories");
                });

            modelBuilder.Entity("MajorProject.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("PStatus")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<int>("ServiceBookingID")
                        .HasColumnType("int");

                    b.Property<string>("UPIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("ServiceBookingID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MajorProject.Models.PaymentMode", b =>
                {
                    b.Property<int>("PaymentModeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentModes")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PaymentModeID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("MajorProject.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("varchar(350)")
                        .HasMaxLength(350);

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MajorProject.Models.ServiceBooking", b =>
                {
                    b.Property<int>("ServiceBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrentLocationOfCar")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Issue")
                        .HasColumnType("int");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.HasKey("ServiceBookingId");

                    b.HasIndex("Issue");

                    b.HasIndex("Service");

                    b.ToTable("ServiceBookings");
                });

            modelBuilder.Entity("MajorProject.Models.Urgency", b =>
                {
                    b.Property<int>("UrgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TimeToReach")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Urgencies")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UrgencyId");

                    b.ToTable("Urgencies");
                });

            modelBuilder.Entity("MajorProject.Models.Car", b =>
                {
                    b.HasOne("MajorProject.Models.CarModel", "CarModels")
                        .WithMany("Cars")
                        .HasForeignKey("CarMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorProject.Models.Customer", "Customers")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MajorProject.Models.CarModel", b =>
                {
                    b.HasOne("MajorProject.Models.CarCompany", "CarCompanies")
                        .WithMany("CarModels")
                        .HasForeignKey("CarCID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MajorProject.Models.Issue", b =>
                {
                    b.HasOne("MajorProject.Models.Car", "Cars")
                        .WithMany("Issues")
                        .HasForeignKey("Car")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorProject.Models.IssueCategory", "IssueCategories")
                        .WithMany("Issues")
                        .HasForeignKey("IssueCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorProject.Models.Urgency", "Urgencies")
                        .WithMany("Issues")
                        .HasForeignKey("Urgency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MajorProject.Models.Payment", b =>
                {
                    b.HasOne("MajorProject.Models.PaymentMode", "PaymentModes")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorProject.Models.ServiceBooking", "ServiceBookings")
                        .WithMany("Payments")
                        .HasForeignKey("ServiceBookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MajorProject.Models.ServiceBooking", b =>
                {
                    b.HasOne("MajorProject.Models.Issue", "Issues")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("Issue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorProject.Models.Service", "Services")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("Service")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
